-- AlterTable
ALTER TABLE "tbl_auth_roles" ALTER COLUMN "createdBy" SET DATA TYPE TEXT,
ALTER COLUMN "updatedBy" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "tbl_expenses" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "vatAmount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "tbl_invoices" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "vatAmount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "tbl_salaries" ALTER COLUMN "amountDue" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "amountPaid" SET DEFAULT 0,
ALTER COLUMN "amountPaid" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "tbl_salaries_draft" ALTER COLUMN "totalAmountDue" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "totalAmountPaid" SET DEFAULT 0,
ALTER COLUMN "totalAmountPaid" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "tbl_users_details" ALTER COLUMN "salary" SET DEFAULT 0,
ALTER COLUMN "salary" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "tbl_users_roles" ALTER COLUMN "createdBy" SET DATA TYPE TEXT;
