export const SUBJECTS = {
  ALL: 'all',
  USER: 'user',
  EXPENSE: 'expense',
  DEPARTMENT: 'department',
  ENTITY: 'entity',
  CATEGORY: 'category',
  STORY: 'story',
  ROLE: 'role',
  PERMISSION: 'permission',
  EMPLOYEE_DETAILS: 'employee_details',
  SALARY_DRAFT: 'salary_draft',
  SALARY: 'salary',
  ACCOUNT: 'account',
  ACCOUNT_TRANSACTION: 'account_transaction',
  CLIENT: 'client',
  PROJECT: 'project',
  INVOICE: 'invoice',
};
